---
- name: Creates backend directory
  file:
    path: ~/backend
    state: directory

- name: "copy files"
  copy:
    src: artifact.tar.gz
    dest: ~/backend
    backup: true
    
- name: Extract backend files
  shell: |
    cd ~/backend
    tar -xvf artifact.tar.gz
    rm artifact.tar.gz

- name: "install dependencies."
  become: yes
  apt:
    name: ["npm"]
    state: latest
    update_cache: yes

#- name: PM2 Stop
#  shell: |
#    pm2 stop default

- name: PM2 Start
  shell: |
    pm2 start npm -- start
